plugins {
    id 'groovy'
    id 'application'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

application {
    mainClass = 'org/example/Main'
}

dependencies {
    implementation 'org.apache.groovy:groovy:5.1.1'
    implementation 'org.apache.groovy:groovy-json:4.0.28'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}